######################
#        WYNNCON KARMA       #
#  written by HowToZombie   #
######################

enabled: true
database: true
ranks:
  0:
    tag: ''
    shortTag: ''
    canRankup: false
    canRankdown: false
    permissions: 0
    subcategoriesEnabled: false
  1:
    tag: '&fTrial '
    shortTag: '&fTr. '
    canRankup: false
    canRankdown: false
    permissions: 0
    subcategoriesEnabled: false
  2:
    tag: '&aNew '
    shortTag: '&a'
    canRankup: true
    rankup: 200
    rankupTo: 3
    canRankdown: false
    permissions: 1
    subcategoriesEnabled: true
    subcategories:
      1: 0
      2: 50
      3: 125
  3:
    tag: '&2'
    shortTag: '&2'
    canRankup: true
    rankup: 600
    rankupTo: 4
    canRankdown: true
    rankdown: 200
    rankdownTo: 2
    permissions: 1
    subcategoriesEnabled: true
    subcategories:
      1: 200
      2: 300
      3: 450
  4:
    tag: '&eAdept '
    shortTag: '&e'
    canRankup: true
    rankup: 1200
    rankupTo: 5
    canRankdown: true
    rankdown: 600
    rankdownTo: 3
    permissions: 1
    subcategoriesEnabled: true
    subcategories:
      1: 600
      2: 800
      3: 1100
  5:
    tag: '&6Elite '
    shortTag: '&6'
    canRankup: false
    canRankdown: true
    rankdown: 1200
    rankdownTo: 4
    permissions: 1
    subcategoriesEnabled: true
    subcategories:
      1: 1400
      2: 1800
      3: 2400
  6:
    tag: '&dExpert '
    shortTag: '&d'
    canRankup: false
    canRankdown: false
    permissions: 1
    subcategoriesEnabled: true
    subcategories:
      1: -1
      2: -1
      3: -1
  7:
    tag: '&5Master '
    shortTag: '&5'
    canRankup: false
    canRankdown: false
    permissions: 1
    subcategoriesEnabled: true
    subcategories:
      1: -1
      2: -1
      3: -1
  8:
    tag: '&cGrandmaster '
    shortTag: '&c'
    canRankup: false
    canRankdown: false
    permissions: 1
    subcategoriesEnabled: true
    subcategories:
      1: -1
      2: -1
      3: -1